//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PapaBobsMegaChallenge.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class PizzaSizes
    {
        public System.Guid Id { get; set; }
        public string Description { get; set; }
        public double Size { get; set; }
        public double Price { get; set; }
    }
}
